language: bash
services: docker

env:
  - VERSION=1.0

install:
  - git clone https://github.com/karelbemelmans/d7-docker-base.git ~/d7-docker-base

before_script:
  - env | sort
  - cd "$VERSION"
  - image="karelbemelmans/d7-docker-base:$VERSION"

script:
  - docker build -t "$image" .

after_script:
  - docker images
