version: '2'
services:
  drupal:
    build: .
    ports:
      - "80:80"
    links:
      - db
      - memcached
  db:
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: drupal
      MYSQL_USER: drupal
      MYSQL_PASSWORD: drupal
  memcached:
    image: memcached
